ci:
  autoupdate_schedule: monthly

exclude: ^zmq/eventloop/minitornado/
repos:
  - repo: local
    hooks:
      - id: constants
        name: constants
        files: "^.*/constants.py"
        description: Generate constants files
        entry: python -m buildutils.constants
        language: python
        pass_filenames: false
        additional_dependencies:
          - ruff
  - repo: https://github.com/executablebooks/mdformat
    rev: 2d496dbc18e31b83a1596685347ffe0b6041daf0  # frozen: 1.0.0
    hooks:
      - id: mdformat
        # Optionally add plugins
        additional_dependencies:
          - mdformat-black
          - mdformat-myst
        exclude: LICENSE.md

  # autoformat and lint Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 6fec9b7edb08fd9989088709d864a7826dc74e80  # frozen: v0.15.12
    hooks:
      - id: ruff
        types_or:
          - python
          - jupyter
          - pyi
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
        types_or:
          - python
          - jupyter
          - pyi
        # don't format zmq/constants.py twice
        exclude: zmq/constants.py

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: d2823d321df3af8f878f7ee3414dc94d037145b9  # frozen: v2.1.0
    hooks:
      - id: mypy
        files: zmq/.*
        # mypy gets the wrong results
        # if we pass specific files instead of the zmq dir
        # no idea why
        pass_filenames: false
        args: [zmq]
        additional_dependencies:
          - tornado
          - types-cffi
          - types-gevent
          - types-paramiko
          - types-pexpect
          - types-tornado

  # github actions security checks
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: a4727cbbcd26d7098e96b9cb738169b59711ae51  # frozen: v1.24.1
    hooks:
      - id: zizmor
        args:
          - --fix=all
        files: .github/workflows/.*.ya?ml

  # stricter config for wheels
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: a4727cbbcd26d7098e96b9cb738169b59711ae51  # frozen: v1.24.1
    hooks:
      - id: zizmor
        name: zizmor-strict
        args:
          - --fix=all
          - --config=zizmor-strict.yaml
        files: \.github/workflows/wheels\.yml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer
