[mypy]
allow_redefinition = True
ignore_missing_imports = True

warn_unused_configs = True
warn_unused_ignores = True
warn_redundant_casts = True

[mypy-zmq.*]
disallow_untyped_calls = False

[mypy-zmq.backend.cffi.*]
ignore_errors = True

[mypy-zmq.backend.cython.*]
ignore_errors = True

[mypy-zmq.eventloop.minitornado.*]
ignore_errors = True
