"""0MQ Constants."""

#
#    Copyright (c) 2010 Brian E. Granger & Min Ragan-Kelley
#
#    This file is part of pyzmq.
#
#    pyzmq is free software; you can redistribute it and/or modify it under
#    the terms of the Lesser GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    pyzmq is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    Lesser GNU General Public License for more details.
#
#    You should have received a copy of the Lesser GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#-----------------------------------------------------------------------------
# Imports
#-----------------------------------------------------------------------------

from libzmq cimport *

#-----------------------------------------------------------------------------
# Python module level constants
#-----------------------------------------------------------------------------

VERSION = ZMQ_VERSION
VERSION_MAJOR = ZMQ_VERSION_MAJOR
VERSION_MINOR = ZMQ_VERSION_MINOR
VERSION_PATCH = ZMQ_VERSION_PATCH
NOBLOCK = ZMQ_NOBLOCK
DONTWAIT = ZMQ_DONTWAIT
POLLIN = ZMQ_POLLIN
POLLOUT = ZMQ_POLLOUT
POLLERR = ZMQ_POLLERR
SNDMORE = ZMQ_SNDMORE
STREAMER = ZMQ_STREAMER
FORWARDER = ZMQ_FORWARDER
QUEUE = ZMQ_QUEUE
PAIR = ZMQ_PAIR
PUB = ZMQ_PUB
SUB = ZMQ_SUB
REQ = ZMQ_REQ
REP = ZMQ_REP
DEALER = ZMQ_DEALER
ROUTER = ZMQ_ROUTER
PULL = ZMQ_PULL
PUSH = ZMQ_PUSH
XPUB = ZMQ_XPUB
XSUB = ZMQ_XSUB
EVENT_CONNECTED = ZMQ_EVENT_CONNECTED
EVENT_CONNECT_DELAYED = ZMQ_EVENT_CONNECT_DELAYED
EVENT_CONNECT_RETRIED = ZMQ_EVENT_CONNECT_RETRIED
EVENT_LISTENING = ZMQ_EVENT_LISTENING
EVENT_BIND_FAILED = ZMQ_EVENT_BIND_FAILED
EVENT_ACCEPTED = ZMQ_EVENT_ACCEPTED
EVENT_ACCEPT_FAILED = ZMQ_EVENT_ACCEPT_FAILED
EVENT_CLOSED = ZMQ_EVENT_CLOSED
EVENT_CLOSE_FAILED = ZMQ_EVENT_CLOSE_FAILED
EVENT_DISCONNECTED = ZMQ_EVENT_DISCONNECTED
EAGAIN = ZMQ_EAGAIN
EINVAL = ZMQ_EINVAL
EFAULT = ZMQ_EFAULT
ENOMEM = ZMQ_ENOMEM
ENODEV = ZMQ_ENODEV
HAUSNUMERO = ZMQ_HAUSNUMERO
ENOTSUP = ZMQ_ENOTSUP
EPROTONOSUPPORT = ZMQ_EPROTONOSUPPORT
ENOBUFS = ZMQ_ENOBUFS
ENETDOWN = ZMQ_ENETDOWN
EADDRINUSE = ZMQ_EADDRINUSE
EADDRNOTAVAIL = ZMQ_EADDRNOTAVAIL
ECONNREFUSED = ZMQ_ECONNREFUSED
EINPROGRESS = ZMQ_EINPROGRESS
ENOTSOCK = ZMQ_ENOTSOCK
EFSM = ZMQ_EFSM
ENOCOMPATPROTO = ZMQ_ENOCOMPATPROTO
ETERM = ZMQ_ETERM
EMTHREAD = ZMQ_EMTHREAD
EAGAIN = ZMQ_EAGAIN
EINVAL = ZMQ_EINVAL
EFAULT = ZMQ_EFAULT
ENOMEM = ZMQ_ENOMEM
ENODEV = ZMQ_ENODEV
ENOTSUP = ZMQ_ENOTSUP
EPROTONOSUPPORT = ZMQ_EPROTONOSUPPORT
ENOBUFS = ZMQ_ENOBUFS
ENETDOWN = ZMQ_ENETDOWN
EADDRINUSE = ZMQ_EADDRINUSE
EADDRNOTAVAIL = ZMQ_EADDRNOTAVAIL
ECONNREFUSED = ZMQ_ECONNREFUSED
EINPROGRESS = ZMQ_EINPROGRESS
ENOTSOCK = ZMQ_ENOTSOCK
EFSM = ZMQ_EFSM
ENOCOMPATPROTO = ZMQ_ENOCOMPATPROTO
ETERM = ZMQ_ETERM
EMTHREAD = ZMQ_EMTHREAD
IO_THREADS = ZMQ_IO_THREADS
MAX_SOCKETS = ZMQ_MAX_SOCKETS
MORE = ZMQ_MORE
IDENTITY = ZMQ_IDENTITY
SUBSCRIBE = ZMQ_SUBSCRIBE
UNSUBSCRIBE = ZMQ_UNSUBSCRIBE
LAST_ENDPOINT = ZMQ_LAST_ENDPOINT
TCP_ACCEPT_FILTER = ZMQ_TCP_ACCEPT_FILTER
RECONNECT_IVL_MAX = ZMQ_RECONNECT_IVL_MAX
SNDTIMEO = ZMQ_SNDTIMEO
RCVTIMEO = ZMQ_RCVTIMEO
SNDHWM = ZMQ_SNDHWM
RCVHWM = ZMQ_RCVHWM
MULTICAST_HOPS = ZMQ_MULTICAST_HOPS
IPV4ONLY = ZMQ_IPV4ONLY
ROUTER_BEHAVIOR = ZMQ_ROUTER_BEHAVIOR
TCP_KEEPALIVE = ZMQ_TCP_KEEPALIVE
TCP_KEEPALIVE_CNT = ZMQ_TCP_KEEPALIVE_CNT
TCP_KEEPALIVE_IDLE = ZMQ_TCP_KEEPALIVE_IDLE
TCP_KEEPALIVE_INTVL = ZMQ_TCP_KEEPALIVE_INTVL
DELAY_ATTACH_ON_CONNECT = ZMQ_DELAY_ATTACH_ON_CONNECT
XPUB_VERBOSE = ZMQ_XPUB_VERBOSE
ROUTER_RAW = ZMQ_ROUTER_RAW
FD = ZMQ_FD
EVENTS = ZMQ_EVENTS
TYPE = ZMQ_TYPE
LINGER = ZMQ_LINGER
RECONNECT_IVL = ZMQ_RECONNECT_IVL
BACKLOG = ZMQ_BACKLOG
AFFINITY = ZMQ_AFFINITY
MAXMSGSIZE = ZMQ_MAXMSGSIZE
HWM = ZMQ_HWM
SWAP = ZMQ_SWAP
MCAST_LOOP = ZMQ_MCAST_LOOP
RECOVERY_IVL_MSEC = ZMQ_RECOVERY_IVL_MSEC
RATE = ZMQ_RATE
RECOVERY_IVL = ZMQ_RECOVERY_IVL
SNDBUF = ZMQ_SNDBUF
RCVBUF = ZMQ_RCVBUF
RCVMORE = ZMQ_RCVMORE

#-----------------------------------------------------------------------------
# Symbols to export
#-----------------------------------------------------------------------------
__all__ = [
  "VERSION",
  "VERSION_MAJOR",
  "VERSION_MINOR",
  "VERSION_PATCH",
  "NOBLOCK",
  "DONTWAIT",
  "POLLIN",
  "POLLOUT",
  "POLLERR",
  "SNDMORE",
  "STREAMER",
  "FORWARDER",
  "QUEUE",
  "PAIR",
  "PUB",
  "SUB",
  "REQ",
  "REP",
  "DEALER",
  "ROUTER",
  "PULL",
  "PUSH",
  "XPUB",
  "XSUB",
  "EVENT_CONNECTED",
  "EVENT_CONNECT_DELAYED",
  "EVENT_CONNECT_RETRIED",
  "EVENT_LISTENING",
  "EVENT_BIND_FAILED",
  "EVENT_ACCEPTED",
  "EVENT_ACCEPT_FAILED",
  "EVENT_CLOSED",
  "EVENT_CLOSE_FAILED",
  "EVENT_DISCONNECTED",
  "EAGAIN",
  "EINVAL",
  "EFAULT",
  "ENOMEM",
  "ENODEV",
  "HAUSNUMERO",
  "ENOTSUP",
  "EPROTONOSUPPORT",
  "ENOBUFS",
  "ENETDOWN",
  "EADDRINUSE",
  "EADDRNOTAVAIL",
  "ECONNREFUSED",
  "EINPROGRESS",
  "ENOTSOCK",
  "EFSM",
  "ENOCOMPATPROTO",
  "ETERM",
  "EMTHREAD",
  "EAGAIN",
  "EINVAL",
  "EFAULT",
  "ENOMEM",
  "ENODEV",
  "ENOTSUP",
  "EPROTONOSUPPORT",
  "ENOBUFS",
  "ENETDOWN",
  "EADDRINUSE",
  "EADDRNOTAVAIL",
  "ECONNREFUSED",
  "EINPROGRESS",
  "ENOTSOCK",
  "EFSM",
  "ENOCOMPATPROTO",
  "ETERM",
  "EMTHREAD",
  "IO_THREADS",
  "MAX_SOCKETS",
  "MORE",
  "IDENTITY",
  "SUBSCRIBE",
  "UNSUBSCRIBE",
  "LAST_ENDPOINT",
  "TCP_ACCEPT_FILTER",
  "RECONNECT_IVL_MAX",
  "SNDTIMEO",
  "RCVTIMEO",
  "SNDHWM",
  "RCVHWM",
  "MULTICAST_HOPS",
  "IPV4ONLY",
  "ROUTER_BEHAVIOR",
  "TCP_KEEPALIVE",
  "TCP_KEEPALIVE_CNT",
  "TCP_KEEPALIVE_IDLE",
  "TCP_KEEPALIVE_INTVL",
  "DELAY_ATTACH_ON_CONNECT",
  "XPUB_VERBOSE",
  "ROUTER_RAW",
  "FD",
  "EVENTS",
  "TYPE",
  "LINGER",
  "RECONNECT_IVL",
  "BACKLOG",
  "AFFINITY",
  "MAXMSGSIZE",
  "HWM",
  "SWAP",
  "MCAST_LOOP",
  "RECOVERY_IVL_MSEC",
  "RATE",
  "RECOVERY_IVL",
  "SNDBUF",
  "RCVBUF",
  "RCVMORE",
]
